FROM nginx:latest

COPY ./index.html /usr/share/nginx/html/index.html

RUN echo "Healthy" > /usr/share/nginx/html/health-check

COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
