name: Deploy NGINX Instance

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_DEFAULT_REGION: us-east-1
  TF_VAR_vpc_cidr: "10.0.0.0/16"
  TF_VAR_public_subnet_cidr_a: "10.0.9.0/24"
  TF_VAR_public_subnet_cidr_b: "10.0.10.0/24"
  TF_VAR_private_subnet_cidr: "10.0.11.0/24"
  TF_VAR_availability_zone_a: "us-east-1a"
  TF_VAR_availability_zone_b: "us-east-1b"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      id: checkout

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.6

    - name: Check AWS Region
      run: |
        echo "AWS Region is ${{ env.AWS_REGION }}"
        echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: "us-east-1"

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
