name: Deploy NGINX Instance

on:
  push:
    branches:
      - main
      - develop

env:
  AWS_DEFAULT_REGION: us-west-2
  TF_VAR_vpc_cidr: "10.0.0.0/16"
  TF_VAR_public_subnet_cidr_a: "10.0.1.0/24"
  TF_VAR_public_subnet_cidr_b: "10.0.2.0/24"
  TF_VAR_private_subnet_cidr: "10.0.3.0/24"
  TF_VAR_availability_zone_a: "us-west-2a"
  TF_VAR_availability_zone_b: "us-west-2b"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan -out=tfplan

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
